- README.md
Şadi Evren ŞEKER düzenli olarak akademik konularda soru cevap videoları çekiyor -- farklı programlama dillerinde playlist'leri var.
> Bilgisayar Kavramları Eklendi

- README.md
Kerem Sevencan'ın yapmış olduğu Flux çevirisi eklendi.
> Flux eklendi

- README.md
> Added NodeJS Section

- .travis.yml
- README.md
tabi bunu travis-ci.org üzerinden aktif etmek gerek.
> travis-ci entegrasyonu

- README.md
Add new turkish resources for Go and Ruby.
> Add new turkish resources

- README.md
Anlamsal Sürümleme Türkçe dokümantasyonu.
> Faydalı link eklendi.

- README.md
Genelde PHP ve codeigniter frameworkü  üzerine started seviyede eğitim ve uygulamaların olduğu bir youtube kanalı.
> Kablosuzkedi - Youtube Kanalı

- README.md
> Git ve GitHub Kullanımı (Link Düzeltildi)

- README.md
Tayfun Erbilen' in kişisel blogunda yayınladığı PHP dersleri
> Videolu ve Yazılı PHP Dersleri

- README.md
Javascript Garden linkini ekledim ve yazım yanlışı vardı onu düzelttim.
> Güncelleme

- README.md
> Data İstanbul

- README.md
frontend istanbul ve python istanbul gruplarının slack bağlantıları eklendi.
> slack grupları kategorisi eklendi

- README.md
1 HTML,
2 Java,
1 Faydalı Link
Ve 1 de Youtube Kanalı eklemesi yaptım.
> Eklemeler yaptım

- README.md
Vault dokümantasyon Türkçeleştirme github deposu.
> Vault dokümantasyon eklendi.

- README.md
Google, Angularjs isimlendirmesini yeniledigi icin ve framework artik bundan sonra Angular olarak anilacagi icin(2 & 4 surumlerinden itibaren) yeni bir baslik ekledim ve bu kategori altina bir kac link ekledim. Ayrica Devnot daki yazinin tam halinide listeye ekledim.
Tesekkurler
> Updated Readme,

- README.md
> Add VNGRS YT channel

- README.md
Nodejs icin gelecegiyazanlar isimli site kaynagi eklendi
> Nodejs / gelecegiyazanlar kaynagi

- README.md
#89 Buradaki issue'ya binaen, linkleri değiştirdim. Hem web sitesi hem de github reposu olarak
> İstihza linklerini değiştirdim

- README.md
Tekil konuları bu şekilde paylaşmak doğru mu ? bilmiyorum, ama ara sıra böyle çeviri şeklinde makaleler yayınlıyorum.
> React Native animasyonlar eklendi

- README.md
İzmir Geliştirici ve Tasarımcı topluluğu Slack kanalı eklendi.
> added new slack channel

- README.md
> fix: remove angulartr.com

- README.md
Ek olarak TestHive Youtube kanali eklendi.
> BDD, ML ve Java hakkinda turkce kaynaklar.

- README.md
> OpenSSL CA Kılavuzu eklendi.

- CONTRIBUTING.md
Şu an için basit bir yapı oluşturdum üzerinde düşünülebilir. Fakat şöyle bir düşüncem daha var, normalde CONTRIBUTING.md dosyası olduğu zaman yukarıda 'Please review the contributing to ...' şeklinde yazı oluyor ve buna tıklayınca gidilebiliyor. Bunu PR mesajını yazacağı yerde nasıl çıkarabiliriz.
Ör: Burada Write alanında mesaj çıkabiliyor. Böyle olması mı iyi, yoksa CONTRIBUTING.md olarak kalması mı? ![](https://cdn-images-1.medium.com/max/2000/1*xASbNMSlAESl7fZh7cyAkw.png)
> CONTRIBUTING.md eklendi

- .github/CONTRIBUTING.md
- deploy.sh
> Fix URLs in contributing.md

- README.md
Katkı çağrısını okudum, projeyi desteklemek amaçlı kendi hazırlamış olduğum videoları eklemek isterim.
> Added TheLastCodeBenders Youtube channel

- README.md
> D başlığı ve D Programlama Dili içerik olarak eklendi.

- README.md
Paul Graham’ın Beating the Averages isimli makalesinin çevirisi
> Yararlı bir makale

- README.md
> Android kısmına blog sayfası ve pdf kitap eklendi

- README.md
> Gemfile nedir çevirisi.

- README.md
Java teknolojileri ile ilgili blog yazılarımın ve videolarımın, Angular 2'nin de blog yazılarının adresini ekledim.
> Java teknolojileri ve Angular2 ile ilgili kaynaklar eklendi.

- README.md
Benim de çorbada turum bulunsun...
> Emrah Yüksel'in PHP ve Laravel Dersleri eklendi

- README.md
> umiitkose.com Android kısmının belirtilmesi

- README.md
Go programlama dili ile web uygulaması geliştirmek adlı içeriğin eklenmesi
> Go programlama diline türkçe kaynak

- README.md
Başlık uzun olduğu için kısaltarak yazdım. Electron hakkında seyrekte olsa bazı kaynaklar var. O yüzden Electron başlığı oluşturdum.
> Electron başlığı ve makale eklendi

- README.md
Merhaba
2 kategori içinde içerik eklendi. Link durumu düzeltildi.
Teşekkürler. Kolay Gelsin
> Jekyll ve Nginx hakkında makale eklendi

- README.md
> Taş attıkta kolumuz mu yoruldu abi... 😄

- README.md
> Bazı İngilizce karakter sorunları çözüldü

- README.md
> Çevirisini yaptığım kitabı ekledim.

- README.md
> Web Odası'nın HTML&CSS oynatma listesi eklendi.

- README.md
Node js eğitim serisi ve Symfony eğitim videoları eklendi
> Node js & Symfony

- README.md
Bir gün önce yazdığım bir makaleyi ekledim.
> Electron ile ilgili 2. makale eklendi

- README.md
Derin Öğrenme(Deep Learning) alanında bizim de türkçe olarak üretilen içerikleri derlediğimiz repomuzun linki eklendi.
Konu başlıklarına link verildi.
> Türkçe Yapay Zeka Kaynakları reposu eklendi

- README.md
> Yeni youtube kanalı.

- README.md
> Added Bot Framework, React Native and Xamarin Blog Posts

- README.md
> AcikAkademi.com un eğitimlerini ekledim.

- README.md
Kirik link'leri direk kaldirdim. 
@gokaygurcan @lacivert abi burasini guncel ve kaliteli bir kaynak haline getirmeye calistigimiz icin kirik linkleri kaldirmaktan cekinmeyin. Travis build'in patlamasi kabul edilebilir bir durum olmamasi gerekiyor. Misal az once kendi domain'imiz www'suz halinde calismiyormus. Travis build log'una bakinca fark ettim.
> Calismayan linkleri kaldirdim

- README.md
Satır 440 - [Laravel İstanbul](http://laravel.istanbul/) ([Kayıt Ol/Giriş Yap](https://laravelistanbul.slack.com))
> laravel.istanbul - slack grubu linki eklendi

- README.md
> 404 hatası veriyordu. Kaldırıldı.

- README.md
Go programlama dili ile ilgili hem giriş hemde orta seviye Türkçe içerik bağlantılarını içerir.
> Golang için yeni bağlantılar eklendi.

- README.md
C programlama dilini bu yaz öğrenmek için kullandığım iki kaynağı eklemek istedim.
> C programlama dili için bağlantılar eklendi.

- README.md
> Javascript closure ve coercion konuları eklendi

- README.md
> Android Eğitim Playlist Eklendi.

- README.md
GNU/Linux ve Kotlin başlıkları eklendi. Docker ve JavaScript başlıkları altına da ilgili makaleler iliştirildi. Yazılım Blogları Türkiye Facebook grubu, faydalı linklere eklendi.
> GNU/Linux, Kotlin, Docker, JavaScript

- README.md
- React, React Native ve JavaScript başlıklarına yeni blog yazıları eklendi.
- Frontend İstanbul youtube kanalı eklendi.
> Yeni linkler eklendi

- README.md
Yusuf Sezer'in yazıları eklendi. **Node JS Blog Yazıları & Eğitimleri** adında bir bağlantı vardı fakat eklediğim bağlantı da bununla aynı içeriği (başlığın mantığını) taşıdığı için 2 diye bir ek ekledim. Bu durum bir sorun oluşturursa düzeltebilirim.
Node.js ile Oyun Yazmak Serisi eklendi. (seriye yeni başladım, her hafta yeni video ve makale yayınlıyorum)
> Node.js ile ilgi makaleler eklendi

- README.md
> Django Uygulamasını Yayına Alma eklendi

- README.md
Merhaba, sanalonyedi adlı youtube kanalımızı ve bu kanalda bulunan videolarımızı ekledim. MongoDB başlığı yoktu onu da ekledim bazı vidolarımızı bu bölüme koydum. Böyle bir liste hazırladığınız için teşekkürler. Çok faydalı görünüyor.
> Sanalonyedi youtube kanalı eğitimleri eklendi.

- README.md
Yeni bir yazı dizisine başlıyorum, Sayfaları tek tek eklemek yerine yazıları listeleyen bir sayfa hazırladım.
> Yeni kaynak eklendi: Django Notlarım - Gökmen G.

- README.md
> Gulp ve Router eklendi

- README.md
> vue.js dersleri eklendi

- README.md
Jargon.ist - Bilgisayar bilimleri jargonu sözlüğü
> Jargon.ist

- README.md
> acik kaynak slack grubu davetiye linki guncellendi

- README.md
Güncel olarak dinlediğim ve yararlı bulduğum podcastleri listeye ekledim.
> Yeni podcastler eklendi.

- README.md
JavaScript ve React Başlıklarına ekleme yapıldı
> JavaScript ve React Başlıklarına ekleme yapıldı

- README.md
> Django Blog Oluşturma Videoları Eklendi #198

- README.md
Vue.js başlığı için video içeriği eklendi
> Vue.js başlığı için video içeriği eklendi

- README.md
Kırık Linkler düzeltildi. https://github.com/fatihacet/turkcekaynaklar-com/issues/220
> Kırık bağlantılar

- README.md
Java, Servlet&JSP, Hibernate/JPA, Spring Framework, Apache yazıları içeren in java we trust linki eklendi.
> Java teknolojileri için link eklendi

- README.md
Airbnb'nin oluşturduğu css stil rehberinin Türkçe çevirisi
> CSS Stil Rehberi

- README.md
> C++ tutorial eklendi

- README.md
> swifthane podcasti eklendi. Ücretli kurs kaldırıldı.

- README.md
> CSS Grid Layout Rehberi eklendi

- README.md
> Güncellendi.

- README.md
Sublime Text 3 Kurulumu ve Popüler Eklentilerinin Yüklenmesi
> Arduino Kategorisi ve Faydalı Linkler Eklendi

- README.md
> Kotlin eğitim videoları serisi eklendi

- README.md
iOS ve Android ile ilgili eklemeleri yaptım sadece Kotlin ve Swift ile ilgili eklemeler kaldı.
> iOS ve Android ile ilgili linkler eklendi.

- README.md
> Sketch App video dersleri eklendi.

- README.md
> Lemi'nin Not Defteri Podcast i eklendi

- README.md
Videoyu bugün izledim, çok hoşuma gitti. Faydalı bir kaynak olduğunu düşünüyorum.
> Fatih Arslan'ın "Soru nasıl sorulur?" videosu eklendi

- README.md
> Fehmi Uyar youtube kanalı eklendi

- README.md
> C++ En İyi Uygulamalar Eklendi.

- README.md
graphql ile ilgili 4 adet yeni çeviri makale eklendi.
> Graphql Kaynakları eklendi.

- README.md
> Dr. Ahmet Bingül'ün C Programlama Dili'ne Giriş derslerinin linki eklenmiştir.

- README.md
Mustafa Murat Coşkun'a ait 48 videoluk Python3 dersleri Youtube Playlist'i eklendi.
> Python 3 Türkçe dersi eklendi.

- README.md
Blockchain Başlığı Açıldı, BlockchainTurk.net Eklendi
> Blockchain Başlığı Açıldı, BlockchainTurk.net Eklendi

- README.md
Python başlığı altına **Türkçe Python Kaynaklar** Github reposu eklendi.
> Türkçe Python kaynakları eklendi.

- README.md
> iOS, Xcode, Swift

- README.md
> Gökhan Şengün'ün Docker İpuçları sayfasının adresi güncellendi.

- README.md
JavaScript'te "Değişmezlik" başlıklı yeni bir yazı eklendi.
> docs(JavaScript): Immutability ile ilgili yeni bir yazı eklendi

- README.md
> Ionic başlığı ve ilgili bir yazı eklendi

- README.md
> iOS geliştiriciler için ML yazıları eklendi

- README.md
> Yazılımcılar için haftasonu okumaları bülteni eklendi.

- README.md
Uçbirim kanalı Youtube Kanalları listesine eklendi
> Uçbirim kanalı Youtube Kanalları listesine eklendi

- README.md
> Vim için videolar eklendi

- README.md
> Dart ve Flutter eklendi

- README.md
> web geliştirici yol haritası

- README.md
> Değişikler yeniden düzenlendi. Eksikler giderildi.

- README.md
Git başlığı altına yeni bir içerik eklendi.
> Git Başlığı Güncelleme

- README.md
> GNU C Kütüphanesi Başvuru Kılavuzu, GNU Bash Başvuru Kılavuzu, GNU/Linux Komutları  eklendi.

- README.md
> added devops turkiye slack group

- README.md
Tasarım desenlerinin basitleştirilmiş Türkçe açıklamaları ve kod örnekleri.
> "İnsanlar için tasarım desenleri" added

- README.md
> flutter eğitim serisi youtube playlisti eklendi.

- README.md
Go, Java, Vue.js ve faydalı linkler kısımlarına yeni türkçe kaynaklar ekledim.
Linkleri kontrol ettim. Hepsi çalışıyor. 
Kendi yazılım blogumda (onbirkod.com) geliştirici arkadaşlara faydası olur düşüncesiyle yazdığım bazı makaleleri paylaştım.
> Go, Java, Vue.js ve faydalı linkler kısmına eklemeler oldu

- README.md
> Satir bosulugu duzeltme

- README.md
> update go resources

- README.md
#298 'de travis erişimi ile alakalı problem olmuştu. Şu anda bu adres üzerinden bağlanabiliyorum.
> Kişisel site link değişikliği

- README.md
> Android bazı linkler update edildi, link eklendi.

- README.md
Blogum'da ve medium hesabımda yayınlamış olduğum bazı yazıları ekledim:
- Sign with Apple
- UIMotion Effect
- SwiftUI ilk bakış
> Yeni swift kaynakları eklendi

- README.md
> n11 php api eklendi.

- README.md
/ping @selimober
> [L140] 502 https://selimober.com/bdd-ye-giris/
/ping @cagricolak
> [L538] 404 https://nscolak.com
> housekeeping

- README.md
Angular ve Laravel kategorilerinde yararlı kaynaklar eklendi.
> Angular ve Laravel güncelleme

- README.md
- Uçbirim kanalının [Vim: Türkçe](https://www.youtube.com/playlist?list=PL10LEMb2yDT0DuX11uAXvWu9QghAZMD2P) oynatma listesindeki videolar kaynak olarak eklendi.
- Twitter'da GIF olarak paylaşım yapan [@vimturkce](https://twitter.com/vimturkce) hesabı da listeye eklendi.
:tada:
> Vim için video kaynaklar eklendi

- README.md
> Dependency Injection makalesi ve Türkay Ürkmez web sitesi eklendi

- README.md
> Android, Kotlin ve Swift ile ilgili blog yazılar eklendi.

- README.md
> Turuncu Pasaport ve Türkçe Doküman eklendi.

- README.md
[Backend Best Practices](https://github.com/futurice/backend-best-practices) kütüphanesinin Türkçe çevirisi eklendi.
> Backend Best Practices

- README.md
> Kotlin, Android, Python, Swift ve Linux blog post linkleri eklendi.

- README.md
> İki Çeviri ("Clean Code For JavaScript" ve "Backend Best Practices")

- README.md
Dokümana dinlemekten keyif aldığım yeni podcastleri ekledim.
> Yeni podcastler eklendi

- README.md
JavaScript bölümüne yeni başlayan eğitim serisine ait bir link ekledim.
> JavaScript new link.

- README.md
> Kişisel makalelerim.

- README.md
> CSS(Sass) Rehberi Oluşturuldu

- README.md
Yazılım geliştirme ile ilgili olarak doğrudan dil ve teknoloji üzerine olmayan genel Türkçe kaliteli içerikler üreten [Prisync Labs YouTube kanalı](https://www.youtube.com/channel/UCAYAwQ-SKG2-o4c5UQcitTQ) eklendi
> Youtube Kanalları: Prisync Labs Eklendi

- README.md
> Rust ile CHIP-8 Emülatörü Geliştirme yazısı eklemesi

- README.md
> Android ve Swift blog yazıları eklendi.

- README.md
2018 sonu çekilen 14 videodan oluşan HTML Dersleri eklendi
> 🎥 HTML Dersleri - Prototürk Eklendi

- README.md
> Kotlin linkleri eklendi.

- README.md
Software Craftsmanship Turkey youtube kanalı eklendi
> Youtube kanalı eklendi

- README.md
İstihza Python3 belgelerinin linki düzeltildi.
> İstihza Python Linki Düzeltildi

- README.md
Kırık Lİnk kaldırıldı ve aynı kişinin farklı bir wordpress videosu eklendi
> Wordpress detayındaki link ve video değiştirildi

- README.md
Ahmet Alp Balkan'ın Google ve Microsoft’ta çalışarak öğrendiklerini, açık kaynaklı altyapı teknolojileri, container'lar ve Kubernetes üzerine tecrübelerini yayınladığı Youtube kanalı.
> Ahmet Alp Balkan Youtube Kanalı Eklendi

- README.md
React.js öğrenmek için kullanabileceğiniz ücretsiz Türkçe kaynak.
> React.js Türkçe Kaynak (Handbook)

- README.md
Android başlığı altına ExoPlayer ile ilgili bir link eklendi.
> Android ile ilgili bir link eklendi.

- README.md
Offset Kavramı Ve Dinamik Dizi Yapımı (2 ve 3 Boyutlu)
> Offset Kavramı Ve Dinamik Dizi Yapımı (2 ve 3 Boyutlu)

- README.md
> ASP.NET,Java ve C# kaynakları eklendi

- README.md
Mustafa Akgül Yazılım Kış Kampında, php eğitimlerinde verdiğimiz ders notları eklendi.
> PHP Eğitim notları eklendi.

- README.md
Uğur Umutluoğlu, Armağan Amcalar ve Haydi Kodlayalım Youtube kanallarını ekledim.
> Adding Youtube channels

- README.md
[Karl Seguin](https://github.com/karlseguin) tarafından yazılmış [The Little Go Book](https://github.com/karlseguin/the-little-go-book) kitabının Türkçe'ye çevirisini yaptım. Bunun bu listede olmasının güzel olacağını düşündüm.
> Add "Go El Kitabı"

- README.md
Kotlin ve Flutter ile ilgili blog yazılarının linkleri eklendi.
Yazılım Cenneti adlı YouTube kanalıda kanal linkleri arasına eklendi.
> Kotlin, Flutter ile ilgili blog yazıları eklendi.

- README.md
> Powershell türkçe kaynak eklendi.

- README.md
Selamlar 👋,
Typescirpt ile ilgili yazdığım makalemi daha fazla kişinin faydalanabilmesi için buraya eklemek istedim.  😀
Sevgiler.
> Typescript başlığı eklendi

- README.md
> Kodlama Vakti Eklendi

- README.md
Kotlin diliyle bir blog yazısı ve video playlist eklendi.
> Kotlin blog yazısı ve video playlist eklendi.

- README.md
Youtube kanallarına AliDogan.Kim eklendi
> Youtube kanalı eklendı

- README.md
Youtube kanallarına ek olarak, Twitch'te programlama ve yazılım ile ilgili yayın yapan kişilerin de listesini oluşturabiliriz düşüncesindeyim sizler de uygun görürseniz.
> Youtube'a ek olarak Twitch kanalları listesi

- README.md
> C#, Go ve Youtube kanallarına ekleme yaptım.

- README.md
Android, Kotlin, SOAP, Rest, Cordova ile ilgili blog yazıları eklendi.
> Android, Kotlin ile ilgili linkler eklendi.

- README.md
> React Native kaynağı eklendi

- README.md
> ReactJs bölümüne Redux Thunk'ın Kullanım Amacı yazısı eklendi.

- README.md
mustafacagri.medium.com'daki Vue.js içerikleri eklendi
> Medium'dan Vue.js içerikleri eklendi

- README.md
Kodluyoruz HTML-Giriş oynatma listesi eklendi
> HTML kaynak eklendi

- README.md
veri bilimi adli sekmenin olusturulmasi ve ilk egitim grubunun eklenmesi
> veri bilimi kaynaklarıyla ilgili bir bolum acilmasi ve ilk kaynagin koyulmasi

- README.md
Design Patterns başlığı ve bu başlığın altına strategy design pattern yazısı eklendi.
> Design Patterns Basligi Eklendi

- README.md
RxJs- Bilinmesi Gereken Operatörler
> RxJs- Bilinmesi Gereken Operatörler eklendi.

- README.md
> Java eğitimi eklendi

- README.md
3 adet blog yazısı linki eklendi.
> iOS ve Android blog yazıları eklendi.

- README.md
> Angular içerikleri eklendi

- README.md
> Flutter kaynagi eklendi.

- README.md
> Laravel mix nedir? eklendi

- README.md
> Android kaynagi eklendi

- README.md
> TypeScript notlari eklendi

- README.md
Detaylı Microsoft C# belgesi sıfırdan en detaylı kaynak olarak ilerleme kaydedebileceğiniz güncel kaynak.
> C# Resmi Kaynak Eklenmesi

- README.md
CSS Konusunda detaylı sayılabilecek seviyede eğitim serisi.
> CSS Eğitimi Eklendi

- README.md
Javascript, React, Faydalı Linkler ve Youtube kanalları bölümlerine eklemeler yaptım. Son zamanlarda çok faydalı bulduğum Discord grupları için yeni bir bölüm oluşturdum.
> Kaynak ekleme

- README.md
- Veri Bilimi başlığına `Hiç Bilmeyenler için Veri Madenciliği` videosu eklendi.
> Hiç bilmeyenler için veri madenciliği videosu eklendi.

- README.md
Türkçe Computer Science(Bilgisayar Bilimleri) eğitimi için başlık ve bağlantı eklendi.
> Bilgisayar Bilimleri başlığı eklendi.

- README.md
"Lokalimde Çalışıyor", is a podcast where Barış Güler and Cabir Bayram talk about the software world. http://lokalimde.works
> docs: :memo: Added "Lokalimde Çalışıyor" link to Podcast list

- README.md
- https://mustafacagri.medium.com/mevn-stack-boilerplate-vue-3-nuxt-3-express-vuetify-201b13618d1a
- https://github.com/mustafacagri/mevn-boilerplate
This pull request adds a [MEVN Stack Boilerplate](https://github.com/mustafacagri/mevn-boilerplate) blog post to the Node.js section
> docs: add a MEVN Stack Boilerplate blog post to the Node.js section
